clear all
close all
%main frame
a = figure('units','normalized','Visible','on','MenuBar','figure','Resize','off','NumberTitle','off','ToolBar','auto');
backgroundcolor = [.814 0.858 0.9245]; 
set(a,'Name','CS504','Color',backgroundcolor);
set(a,'position',[0,0 .90,.72]);
movegui(a,'center');
subplot('Position',[0.33 0.06 .41 0.85],'color',[0 0 0],'XTick',[],'YTick',[],'Box','on','units','normalized');
h=findobj(gca);
set(h,'xcolor',[1 0 0],'ycolor',[1 0 0] );

uicontrol('Parent',a,...
      'Style','PushButton',...
      'Position',[5 600 120 30],...
      'Backgroundcolor',backgroundcolor,...
      'String','Load data',...
      'fontname','Times New Roman',...
      'callback','load_data;',...
      'FontSize',10,...
      'visible','on',...
      'Tag','load_data');
 
  
  
%********************************************************************
%UNIVARIATE DATA
%********************************************************************
hput = uipanel('Parent', a,...
      'Title','UNIVARIATE DATA','FontSize',13,...
                'BackgroundColor',backgroundcolor,'fontname','Times New Roman',...
                'Position',[.0 .45 .16 .46],'visible','on','Tag','panttest');
  uicontrol('Parent', a,...
    'Style','PushButton',...
    'Position',[5 530 120 30],...
     'Backgroundcolor',backgroundcolor,...
     'String','Display Descip stat',...
     'fontname','Times New Roman',...
     'callback','S_desc;',...
     'FontSize',10,...
     'visible','on')
     
  uicontrol('Parent',a,...
      'Style','PushButton',...
      'Position',[5 480 120 30],...
      'Backgroundcolor',backgroundcolor,...
      'String','Display Histogram',...
      'fontname','Times New Roman',...
      'callback','D_hist;',...
      'FontSize',10,...
      'visible','on')
    
  uicontrol('Parent',a,...
      'Style','PushButton',...
      'Position',[5 430 120 30],...
      'Backgroundcolor',backgroundcolor,...
      'String','Fit Histogram',...
      'fontname','Times New Roman',...
      'callback','fit_h;',...
      'FontSize',10,...
      'visible','on')
      
  uicontrol('Parent',a,...
      'Style','PushButton',...
      'Position',[5 380 120 30],...
      'Backgroundcolor',backgroundcolor,...
      'String','Display NormPlot',...
      'fontname','Times New Roman',...
      'callback','D_normp;',...
      'FontSize',10,...
      'visible','on',...
      'Tag','D_normp');
  uicontrol('Parent',a,...
      'Style','PushButton',...
      'Position',[5 330 120 30],...
      'Backgroundcolor',backgroundcolor,...
      'String','Display Boxplot',...
      'fontname','Times New Roman',...
      'callback','D_Boxp;',...
      'FontSize',10,...
      'visible','on')
      
  uicontrol('Parent', a,...
      'Style','PushButton',...
      'Position',[5 30 100 30],...
      'Backgroundcolor',backgroundcolor,...
      'String','Exit',...
      'fontname','Times New Roman',...
      'callback','Exitfigure;',...
      'FontSize',10,...
      'visible','on')
      
  %************************************************************************
  %     BIVARIATE DATA
  %************************************************************************
   hpbt = uipanel('Parent', a,...
      'Title','BIVARIATE DATA','FontSize',13,...
                'BackgroundColor',backgroundcolor,'fontname','Times New Roman',...
                'Position',[.165 .66 .14 .25],'visible','on','Tag','panttest');
   uicontrol('Parent', a,...
      'Style','PushButton',...
      'Position',[230 530 120 30],...
      'Backgroundcolor',backgroundcolor,...
      'String','Student t_test',...
      'fontname','Times New Roman',...
      'callback','XXXXXXX;',...
      'FontSize',10,...
      'visible','on')
      
  uicontrol('Parent',a,...
     'Style','checkbox',...
     'Position',[230 500 20 20],...
      'Backgroundcolor',[.814 0.858 0.9245],...
      'String','',...
      'Value',1,...
      'fontname','Times New Roman',...
      'FontSize',10,...
      'visible','on');
      
   uicontrol('Parent',a,...
     'Style','text',...
     'Position',[250 497 140 20],...
      'Backgroundcolor',[.814 0.858 0.9245],...
      'String','Parametric test',...
      'HorizontalAlignment','left',...
      'fontname','Times New Roman',...
      'FontSize',10,...
      'visible','on');
      
   uicontrol('Parent',a,...
     'Style','checkbox',...
     'Position',[230 470 20 20],...
      'Backgroundcolor',[.814 0.858 0.9245],...
      'String','',...
      'Value',0,...
      'fontname','Times New Roman',...
      'FontSize',10,...
      'visible','on')
        
   uicontrol('Parent',a,...
     'Style','text',...
     'Position',[250 467 140 20],...
      'Backgroundcolor',[.814 0.858 0.9245],...
      'String','Non parametric test',...
      'HorizontalAlignment','left',...
      'fontname','Times New Roman',...
      'FontSize',10,...
      'visible','on')
      

 %************************************************************************
  %     TRIVARIATE DATA
  %************************************************************************  
  
  hptt = uipanel('Parent', a,...
      'Title','TRIVARIATE DATA','FontSize',13,...
                'BackgroundColor',backgroundcolor,'fontname','Times New Roman',...
                'Position',[.165 .40 .14 .25],'visible','on','Tag','panttest');
  
  uicontrol('Parent', a,...
      'Style','PushButton',...
      'Position',[230 360 120 30],...
      'Backgroundcolor',backgroundcolor,...
      'String','ANOVA',...
      'fontname','Times New Roman',...
      'callback','XXXXXXX;',...
      'FontSize',10,...
      'visible','on')
      
  uicontrol('Parent',a,...
     'Style','checkbox',...
     'Position',[230 330 20 20],...
      'Backgroundcolor',[.814 0.858 0.9245],...
      'String','',...
      'Value',1,...
      'fontname','Times New Roman',...
      'FontSize',10,...
      'visible','on')
      
   uicontrol('Parent',a,...
     'Style','text',...
     'Position',[250 327 140 20],...
      'Backgroundcolor',[.814 0.858 0.9245],...
      'String','Parametric test',...
      'HorizontalAlignment','left',...
      'fontname','Times New Roman',...
      'FontSize',10,...
      'visible','on');
  
   uicontrol('Parent',a,...
     'Style','checkbox',...
     'Position',[230 300 20 20],...
      'Backgroundcolor',[.814 0.858 0.9245],...
      'String','',...
      'Value',0,...
      'fontname','Times New Roman',...
      'FontSize',10,...
      'visible','on')
      
   uicontrol('Parent',a,...
     'Style','text',...
     'Position',[250 297 140 20],...
      'Backgroundcolor',[.814 0.858 0.9245],...
      'String','Non parametric test',...
      'HorizontalAlignment','left',...
      'fontname','Times New Roman',...
      'FontSize',10,...
      'visible','on')
      
  
   %************************************************************************
  %     MULTIVARIATE DATA
  %************************************************************************  
      
       hpmt = uipanel('Parent', a,...
      'Title','MULTIVARIATE DATA','FontSize',13,...
                'BackgroundColor',backgroundcolor,'fontname','Times New Roman',...
                'Position',[.165 .14 .14 .25],'visible','on','Tag','panttest');
       uicontrol('Parent', a,...
      'Style','PushButton',...
      'Position',[230 190 120 30],...
      'Backgroundcolor',backgroundcolor,...
      'String','PCA',...
      'fontname','Times New Roman',...
      'callback','XXXXXXX;',...
      'FontSize',10,...
      'visible','on')
      
  
   uicontrol('Parent',a,...
     'Style','checkbox',...
     'Position',[230 160 20 20],...
      'Backgroundcolor',[.814 0.858 0.9245],...
      'String','',...
      'Value',1,...
      'fontname','Times New Roman',...
      'FontSize',10,...
      'visible','on')
       
   uicontrol('Parent',a,...
     'Style','text',...
     'Position',[250 157 140 20],...
      'Backgroundcolor',[.814 0.858 0.9245],...
      'String','Reduce to 2D',...
      'HorizontalAlignment','left',...
      'fontname','Times New Roman',...
      'FontSize',10,...
      'visible','on')
      
   uicontrol('Parent',a,...
     'Style','checkbox',...
     'Position',[230 130 20 20],...
      'Backgroundcolor',[.814 0.858 0.9245],...
      'String','',...
      'Value',0,...
      'fontname','Times New Roman',...
      'FontSize',10,...
      'visible','on')
        
   uicontrol('Parent',a,...
     'Style','text',...
     'Position',[250 127 140 20],...
      'Backgroundcolor',[.814 0.858 0.9245],...
      'String','Reduce to 3D',...
      'HorizontalAlignment','left',...
      'fontname','Times New Roman',...
      'FontSize',10,...
      'visible','on')
       
    uicontrol('Parent',a,...
     'Style','PushButton',...
     'Position',[250 100 140 20],...
      'Backgroundcolor',[.814 0.858 0.9245],...
      'String','save scores',...
      'HorizontalAlignment','center',...
      'fontname','Times New Roman',...
      'FontSize',10,...
      'visible','on')
              
  
  %************************************************************************
  hps = uipanel('Parent', a,...
      'Title','RESULTS','FontSize',13,...
                'BackgroundColor',backgroundcolor,'fontname','Times New Roman',...
                'Position',[.75 .07 .24 .86],'visible','on','Tag','panel');
      uicontrol('Parent',hps,...
      'Style','text','Position',[0 500 150 30],'Backgroundcolor',...
      backgroundcolor,'String','Mean:','fontname','Times New Roman','FontSize',10,'visible','off','Tag','mean');
      uicontrol('Parent',hps,...
      'Style','text','Position',[160 500 40 30],'Backgroundcolor',...
      backgroundcolor,'String','','fontname','Times New Roman','FontSize',10,'visible','on','Tag','textmean');
  
  uicontrol('Parent',hps,...
      'Style','text','Position',[0 470 150 30],'Backgroundcolor',...
      backgroundcolor,'String','Standard Error:','fontname','Times New Roman','FontSize',10,'visible','off','Tag','stdE');
      uicontrol('Parent',hps,...
      'Style','text','Position',[160 470 60 30],'Backgroundcolor',...
      backgroundcolor,'String','','fontname','Times New Roman','FontSize',10,'visible','on','Tag','textstdE');
  
  uicontrol('Parent',hps,...
      'Style','text','Position',[0 440 130 30],'Backgroundcolor',...
      backgroundcolor,'String','CI at 95%:','fontname','Times New Roman','FontSize',10,'visible','off','Tag','CI');
      uicontrol('Parent',hps,...
      'Style','text','Position',[160 440 40 30],'Backgroundcolor',...
      backgroundcolor,'String','','fontname','Times New Roman','FontSize',10,'visible','on','Tag','textCI1');
      uicontrol('Parent',hps,...
      'Style','text','Position',[200 440 40 30],'Backgroundcolor',...
      backgroundcolor,'String','','fontname','Times New Roman','FontSize',10,'visible','on','Tag','textCI2');
  
  uicontrol('Parent',hps,...
      'Style','text','Position',[0 410 150 30],'Backgroundcolor',...
      backgroundcolor,'String','Median:','fontname','Times New Roman','FontSize',10,'visible','off','Tag','Median');
      uicontrol('Parent',hps,...
      'Style','text','Position',[160 410 40 30],'Backgroundcolor',...
      backgroundcolor,'String','','fontname','Times New Roman','FontSize',10,'visible','on','Tag','textmedian');
    
  uicontrol('Parent',hps,...
      'Style','text','Position',[0 380 150 30],'Backgroundcolor',...
      backgroundcolor,'String','Mode:','fontname','Times New Roman','FontSize',10,'visible','off','Tag','Mode');
      uicontrol('Parent',hps,...
      'Style','text','Position',[160 380 40 30],'Backgroundcolor',...
      backgroundcolor,'String','','fontname','Times New Roman','FontSize',10,'visible','on','Tag','textmode');
  
  uicontrol('Parent',hps,...
      'Style','text','Position',[0 350 150 30],'Backgroundcolor',...
      backgroundcolor,'String','Standard deviation:','fontname','Times New Roman','FontSize',10,'visible','off','Tag','std');
      uicontrol('Parent',hps,...
      'Style','text','Position',[160 350 40 30],'Backgroundcolor',...
      backgroundcolor,'String','','fontname','Times New Roman','FontSize',10,'visible','on','Tag','textstd');
  
  uicontrol('Parent',hps,...
      'Style','text','Position',[0 320 150 30],'Backgroundcolor',...
      backgroundcolor,'String','Sample variance:','fontname','Times New Roman','FontSize',10,'visible','off','Tag','var');
      uicontrol('Parent',hps,...
      'Style','text','Position',[160 320 40 30],'Backgroundcolor',...
      backgroundcolor,'String','','fontname','Times New Roman','FontSize',10,'visible','on','Tag','textvar');
  
  uicontrol('Parent',hps,...
      'Style','text','Position',[0 290 150 30],'Backgroundcolor',...
      backgroundcolor,'String','Kurtosis:','fontname','Times New Roman','FontSize',10,'visible','off','Tag','ku');
      uicontrol('Parent',hps,...
      'Style','text','Position',[160 290 40 30],'Backgroundcolor',...
      backgroundcolor,'String','','fontname','Times New Roman','FontSize',10,'visible','on','Tag','textku');
  
  uicontrol('Parent',hps,...
      'Style','text','Position',[0 260 150 30],'Backgroundcolor',...
      backgroundcolor,'String','Skewness:','fontname','Times New Roman','FontSize',10,'visible','off','Tag','sk');
      uicontrol('Parent',hps,...
      'Style','text','Position',[160 260 40 30],'Backgroundcolor',...
      backgroundcolor,'String','','fontname','Times New Roman','FontSize',10,'visible','on','Tag','textsk');
  
  uicontrol('Parent',hps,...
      'Style','text','Position',[0 230 150 30],'Backgroundcolor',...
      backgroundcolor,'String','Range:','fontname','Times New Roman','FontSize',10,'visible','off','Tag','range');
      uicontrol('Parent',hps,...
      'Style','text','Position',[160 230 40 30],'Backgroundcolor',...
      backgroundcolor,'String','','fontname','Times New Roman','FontSize',10,'visible','on','Tag','textrange');
  
  uicontrol('Parent',hps,...
      'Style','text','Position',[0 200 150 30],'Backgroundcolor',...
      backgroundcolor,'String','Minimum:','fontname','Times New Roman','FontSize',10,'visible','off','Tag','Min');
      uicontrol('Parent',hps,...
      'Style','text','Position',[160 200 40 30],'Backgroundcolor',...
      backgroundcolor,'String','','fontname','Times New Roman','FontSize',10,'visible','on','Tag','textmin');
  
  uicontrol('Parent',hps,...
      'Style','text','Position',[0 170 150 30],'Backgroundcolor',...
      backgroundcolor,'String','Maximum:','fontname','Times New Roman','FontSize',10,'visible','off','Tag','Max');
      uicontrol('Parent',hps,...
      'Style','text','Position',[160 170 40 30],'Backgroundcolor',...
      backgroundcolor,'String','','fontname','Times New Roman','FontSize',10,'visible','on','Tag','textmax');
  
  uicontrol('Parent',hps,...
      'Style','text','Position',[0 140 150 30],'Backgroundcolor',...
      backgroundcolor,'String','Sum:','fontname','Times New Roman','FontSize',10,'visible','off','Tag','Sum');
      uicontrol('Parent',hps,...
      'Style','text','Position',[160 140 40 30],'Backgroundcolor',...
      backgroundcolor,'String','','fontname','Times New Roman','FontSize',10,'visible','on','Tag','textsum');
  
  uicontrol('Parent',hps,...
      'Style','text','Position',[0 110 150 30],'Backgroundcolor',...
      backgroundcolor,'String','Count:','fontname','Times New Roman','FontSize',10,'visible','off','Tag','Count');
      uicontrol('Parent',hps,...
      'Style','text','Position',[160 110 40 30],'Backgroundcolor',...
      backgroundcolor,'String','','fontname','Times New Roman','FontSize',10,'visible','on','Tag','textcount');
  
  
  
 
  
  
  
  